version: '3.7'
services:

    app:
        build: app

    calc:
        build: calc

    sum:
        build: sum

    sub:
        build: sub

    mult:
        build: mult

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - app
           - calc
           - sum
           - sub
           - mult